print('Nhập 3 số a b và c') 
a = input('Nhập số a ')
b = input('Nhập số b ')
c = input('Nhập số c ')
t = float(a)+float(b)+float(c)
z = float(a)*float(b)*float(c)
x = float(a)-float(b)*float(c)
y = float(a)-float(b)-float(c)
print('Tổng là ' + str(t))
print('Hiệu là ' + str(y))
print('Gọi biểu thức a-b*c là biểu thức 1 ')
print('Kết quả biểu thức 1 là ' + str(x))
print('Tích là ' + str(z))